name: Build Panopto Keyboard Controller chrome extension
on: push

permissions:
  contents: write

jobs:
  build-extension:
    runs-on: ubuntu-24.04
    env:
      VERSION: ""
      SHORT_COMMIT: ""

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Extract commit metadata
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "SHORT_COMMIT=$(echo ${GITHUB_SHA} | cut -c1-6)" >> $GITHUB_ENV
      
      - name: Set up google-chrome
        run: sudo apt-get -y install google-chrome-stable
      
      - name: Bump version in manifest.json
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          jq --arg version "${{ env.VERSION }}" '.version=$version' panopto_keyboard_controller/manifest.json > panopto_keyboard_controller/manifest_with_version.json.tmp
          mv panopto_keyboard_controller/manifest_with_version.json.tmp panopto_keyboard_controller/manifest.json
      
      - name: Build extension
        run: |
          mkdir output
          google-chrome-stable --pack-extension=panopto_keyboard_controller
          zip -r panopto_keyboard_controller.zip panopto_keyboard_controller/
          cp panopto_keyboard_controller.crx output/panopto_keyboard_controller-${{ env.SHORT_COMMIT }}.crx
          cp panopto_keyboard_controller.zip output/panopto_keyboard_controller-${{ env.SHORT_COMMIT }}.zip
          cp -r panopto_keyboard_controller/icons output/icons-${{ env.SHORT_COMMIT }}
      
      - name: Upload crx artifact
        uses: actions/upload-artifact@v4
        with:
            name: build-artifacts-${{ env.SHORT_COMMIT }}
            path: output/
            retention-days: 7

      - name: Rename extension with version
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          mv panopto_keyboard_controller.crx output/panopto_keyboard_controller-v${{ env.VERSION }}.crx
          mv panopto_keyboard_controller.zip output/panopto_keyboard_controller-v${{ env.VERSION }}.zip
          cp panopto_keyboard_controller/icons/icon-128.png output/icon-128-v${{ env.VERSION }}.png

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ env.VERSION }}
          files: |
            output/panopto_keyboard_controller-v${{ env.VERSION }}.crx
            output/panopto_keyboard_controller-v${{ env.VERSION }}.zip
            output/icon-128-v${{ env.VERSION }}.png
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
